id: P000383
initial_creation_type: ocr
created_at: 17/03/2020
last_modified_at: 2021-12-16 15:37:08.744726
source_metadata:
  id: bdr:W1KG22269
  title: ལྷ་མོའི་ཟློས་གར་གྱི་འཁྲབ་གཞུང་དྭངས་ཤེལ་མེ་ལོང་།
  author: ''
  volumes:
    eba083e2c7ec4e04a389869ef4d7c860:
      image_group_id: I1KG22317
      title: Volume 1 of lha mo'i zlos gar gyi 'khrab gzhung dwangs shel me long /
      volume_number: 1
      total_pages: 196
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
